### ISSUE TITLE
Linter showing less accurate results than ansible-lint

### ISSUE THREAD

**Issue by caseylang** [mschuchard/linter-ansible-linting#7]
It seems that this linter is showing less accurate results than the underlying `ansible-lint`:
![screen shot 2016-09-28 at 5 05 36 pm](https://cloud.githubusercontent.com/assets/586829/18934184/fa8ab47e-859d-11e6-84c8-64efd9fad377.png)
![screen shot 2016-09-28 at 5 04 46 pm](https://cloud.githubusercontent.com/assets/586829/18934185/fae830b8-859d-11e6-84af-65818644a640.png)

Atom version: 1.10.2
language-ansible: 0.1.11
linter-ansible-linting: 1.2.0
linter: 1.11.16
ansible-lint: 3.3.0

Happy to provide additional information if needed.

**Comment by mschuchard** [comment]
The purpose of ansible-lint is for style linting. Ansible-lint happens to run a syntax check before doing style linting, because people were opening issues about what they thought were ansible-lint bugs that were really syntax errors in their playbooks.

If you want syntax linting, give linter-ansible-syntax a shot (except that I havent finished writing the code to trick it into linting individual task files). It is equipped for displaying syntax error info.

Speaking of which, how did you get ansible-lint to execute on a task file? it is only supposed to work on playbook files and role directories. I might need to summon Will Thames here unless you can shed some light on it.

**Comment by mschuchard** [comment]
Oh I see. [This happened](https://github.com/willthames/ansible-lint/commit/48777db356690406d15a5512f232d86d050d90ae) as an interesting side effect to my issue at willthames/ansible-lint#193.

I need to write some code for this new ability to lint any task list.

I am going to take some time to think about whether linter-ansible-syntax should start using ansible-lint for syntax linting now...

**Comment by mschuchard** [comment]
Soft ping: eighteen days with no reply.

**Comment by caseylang** [comment]
Sorry, I didn't realize I had a pending question. I didn't do anything except pass ansible-lint the path to the file.

**Comment by mschuchard** [comment]
Oh, I should I have been more specific. I was looking for acknowledgement that linter-ansible-linting is not going to output YAML syntax errors to the display, as its purpose is merely to output style warnings where appropriate and to output clean errors when they show up (I can't actually remember why I implemented that functionality in the first place except to maybe help users debug stack traces more easily and to not have an annoying Atom notification error).

You want either linter-ansible-syntax or a YAML syntax linter for this purpose.

**Comment by caseylang** [comment]
Great thanks!

**Comment by mschuchard** [comment]
So linter-js-yaml probably is not going to be a good candidate to add language `['source.ansible']` to, so I need to keep pursuing the ansible playbook workaround for linter-ansible-syntax.

**Comment by Kami-no** [comment]
Plz parse syntax errors from ansible-linter. I've to check console for syntax errors all the time.
